// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package create

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type KindClusterKindConfig struct {
	ApiVersion              string                           `pulumi:"apiVersion"`
	ContainerdConfigPatches []string                         `pulumi:"containerdConfigPatches"`
	Kind                    string                           `pulumi:"kind"`
	Networking              *KindClusterKindConfigNetworking `pulumi:"networking"`
	Nodes                   []KindClusterKindConfigNode      `pulumi:"nodes"`
}

// KindClusterKindConfigInput is an input type that accepts KindClusterKindConfigArgs and KindClusterKindConfigOutput values.
// You can construct a concrete instance of `KindClusterKindConfigInput` via:
//
//	KindClusterKindConfigArgs{...}
type KindClusterKindConfigInput interface {
	pulumi.Input

	ToKindClusterKindConfigOutput() KindClusterKindConfigOutput
	ToKindClusterKindConfigOutputWithContext(context.Context) KindClusterKindConfigOutput
}

type KindClusterKindConfigArgs struct {
	ApiVersion              pulumi.StringInput                      `pulumi:"apiVersion"`
	ContainerdConfigPatches pulumi.StringArrayInput                 `pulumi:"containerdConfigPatches"`
	Kind                    pulumi.StringInput                      `pulumi:"kind"`
	Networking              KindClusterKindConfigNetworkingPtrInput `pulumi:"networking"`
	Nodes                   KindClusterKindConfigNodeArrayInput     `pulumi:"nodes"`
}

func (KindClusterKindConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*KindClusterKindConfig)(nil)).Elem()
}

func (i KindClusterKindConfigArgs) ToKindClusterKindConfigOutput() KindClusterKindConfigOutput {
	return i.ToKindClusterKindConfigOutputWithContext(context.Background())
}

func (i KindClusterKindConfigArgs) ToKindClusterKindConfigOutputWithContext(ctx context.Context) KindClusterKindConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigOutput)
}

func (i KindClusterKindConfigArgs) ToKindClusterKindConfigPtrOutput() KindClusterKindConfigPtrOutput {
	return i.ToKindClusterKindConfigPtrOutputWithContext(context.Background())
}

func (i KindClusterKindConfigArgs) ToKindClusterKindConfigPtrOutputWithContext(ctx context.Context) KindClusterKindConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigOutput).ToKindClusterKindConfigPtrOutputWithContext(ctx)
}

// KindClusterKindConfigPtrInput is an input type that accepts KindClusterKindConfigArgs, KindClusterKindConfigPtr and KindClusterKindConfigPtrOutput values.
// You can construct a concrete instance of `KindClusterKindConfigPtrInput` via:
//
//	        KindClusterKindConfigArgs{...}
//
//	or:
//
//	        nil
type KindClusterKindConfigPtrInput interface {
	pulumi.Input

	ToKindClusterKindConfigPtrOutput() KindClusterKindConfigPtrOutput
	ToKindClusterKindConfigPtrOutputWithContext(context.Context) KindClusterKindConfigPtrOutput
}

type kindClusterKindConfigPtrType KindClusterKindConfigArgs

func KindClusterKindConfigPtr(v *KindClusterKindConfigArgs) KindClusterKindConfigPtrInput {
	return (*kindClusterKindConfigPtrType)(v)
}

func (*kindClusterKindConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**KindClusterKindConfig)(nil)).Elem()
}

func (i *kindClusterKindConfigPtrType) ToKindClusterKindConfigPtrOutput() KindClusterKindConfigPtrOutput {
	return i.ToKindClusterKindConfigPtrOutputWithContext(context.Background())
}

func (i *kindClusterKindConfigPtrType) ToKindClusterKindConfigPtrOutputWithContext(ctx context.Context) KindClusterKindConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigPtrOutput)
}

type KindClusterKindConfigOutput struct{ *pulumi.OutputState }

func (KindClusterKindConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KindClusterKindConfig)(nil)).Elem()
}

func (o KindClusterKindConfigOutput) ToKindClusterKindConfigOutput() KindClusterKindConfigOutput {
	return o
}

func (o KindClusterKindConfigOutput) ToKindClusterKindConfigOutputWithContext(ctx context.Context) KindClusterKindConfigOutput {
	return o
}

func (o KindClusterKindConfigOutput) ToKindClusterKindConfigPtrOutput() KindClusterKindConfigPtrOutput {
	return o.ToKindClusterKindConfigPtrOutputWithContext(context.Background())
}

func (o KindClusterKindConfigOutput) ToKindClusterKindConfigPtrOutputWithContext(ctx context.Context) KindClusterKindConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v KindClusterKindConfig) *KindClusterKindConfig {
		return &v
	}).(KindClusterKindConfigPtrOutput)
}

func (o KindClusterKindConfigOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v KindClusterKindConfig) string { return v.ApiVersion }).(pulumi.StringOutput)
}

func (o KindClusterKindConfigOutput) ContainerdConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v KindClusterKindConfig) []string { return v.ContainerdConfigPatches }).(pulumi.StringArrayOutput)
}

func (o KindClusterKindConfigOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v KindClusterKindConfig) string { return v.Kind }).(pulumi.StringOutput)
}

func (o KindClusterKindConfigOutput) Networking() KindClusterKindConfigNetworkingPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfig) *KindClusterKindConfigNetworking { return v.Networking }).(KindClusterKindConfigNetworkingPtrOutput)
}

func (o KindClusterKindConfigOutput) Nodes() KindClusterKindConfigNodeArrayOutput {
	return o.ApplyT(func(v KindClusterKindConfig) []KindClusterKindConfigNode { return v.Nodes }).(KindClusterKindConfigNodeArrayOutput)
}

type KindClusterKindConfigPtrOutput struct{ *pulumi.OutputState }

func (KindClusterKindConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KindClusterKindConfig)(nil)).Elem()
}

func (o KindClusterKindConfigPtrOutput) ToKindClusterKindConfigPtrOutput() KindClusterKindConfigPtrOutput {
	return o
}

func (o KindClusterKindConfigPtrOutput) ToKindClusterKindConfigPtrOutputWithContext(ctx context.Context) KindClusterKindConfigPtrOutput {
	return o
}

func (o KindClusterKindConfigPtrOutput) Elem() KindClusterKindConfigOutput {
	return o.ApplyT(func(v *KindClusterKindConfig) KindClusterKindConfig {
		if v != nil {
			return *v
		}
		var ret KindClusterKindConfig
		return ret
	}).(KindClusterKindConfigOutput)
}

func (o KindClusterKindConfigPtrOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KindClusterKindConfig) *string {
		if v == nil {
			return nil
		}
		return &v.ApiVersion
	}).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigPtrOutput) ContainerdConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *KindClusterKindConfig) []string {
		if v == nil {
			return nil
		}
		return v.ContainerdConfigPatches
	}).(pulumi.StringArrayOutput)
}

func (o KindClusterKindConfigPtrOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KindClusterKindConfig) *string {
		if v == nil {
			return nil
		}
		return &v.Kind
	}).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigPtrOutput) Networking() KindClusterKindConfigNetworkingPtrOutput {
	return o.ApplyT(func(v *KindClusterKindConfig) *KindClusterKindConfigNetworking {
		if v == nil {
			return nil
		}
		return v.Networking
	}).(KindClusterKindConfigNetworkingPtrOutput)
}

func (o KindClusterKindConfigPtrOutput) Nodes() KindClusterKindConfigNodeArrayOutput {
	return o.ApplyT(func(v *KindClusterKindConfig) []KindClusterKindConfigNode {
		if v == nil {
			return nil
		}
		return v.Nodes
	}).(KindClusterKindConfigNodeArrayOutput)
}

type KindClusterKindConfigNetworking struct {
	ApiServerAddress  *string `pulumi:"apiServerAddress"`
	ApiServerPort     *int    `pulumi:"apiServerPort"`
	DisableDefaultCni *bool   `pulumi:"disableDefaultCni"`
	IpFamily          *string `pulumi:"ipFamily"`
	KubeProxyMode     *string `pulumi:"kubeProxyMode"`
	PodSubnet         *string `pulumi:"podSubnet"`
	ServiceSubnet     *string `pulumi:"serviceSubnet"`
}

// KindClusterKindConfigNetworkingInput is an input type that accepts KindClusterKindConfigNetworkingArgs and KindClusterKindConfigNetworkingOutput values.
// You can construct a concrete instance of `KindClusterKindConfigNetworkingInput` via:
//
//	KindClusterKindConfigNetworkingArgs{...}
type KindClusterKindConfigNetworkingInput interface {
	pulumi.Input

	ToKindClusterKindConfigNetworkingOutput() KindClusterKindConfigNetworkingOutput
	ToKindClusterKindConfigNetworkingOutputWithContext(context.Context) KindClusterKindConfigNetworkingOutput
}

type KindClusterKindConfigNetworkingArgs struct {
	ApiServerAddress  pulumi.StringPtrInput `pulumi:"apiServerAddress"`
	ApiServerPort     pulumi.IntPtrInput    `pulumi:"apiServerPort"`
	DisableDefaultCni pulumi.BoolPtrInput   `pulumi:"disableDefaultCni"`
	IpFamily          pulumi.StringPtrInput `pulumi:"ipFamily"`
	KubeProxyMode     pulumi.StringPtrInput `pulumi:"kubeProxyMode"`
	PodSubnet         pulumi.StringPtrInput `pulumi:"podSubnet"`
	ServiceSubnet     pulumi.StringPtrInput `pulumi:"serviceSubnet"`
}

func (KindClusterKindConfigNetworkingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*KindClusterKindConfigNetworking)(nil)).Elem()
}

func (i KindClusterKindConfigNetworkingArgs) ToKindClusterKindConfigNetworkingOutput() KindClusterKindConfigNetworkingOutput {
	return i.ToKindClusterKindConfigNetworkingOutputWithContext(context.Background())
}

func (i KindClusterKindConfigNetworkingArgs) ToKindClusterKindConfigNetworkingOutputWithContext(ctx context.Context) KindClusterKindConfigNetworkingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigNetworkingOutput)
}

func (i KindClusterKindConfigNetworkingArgs) ToKindClusterKindConfigNetworkingPtrOutput() KindClusterKindConfigNetworkingPtrOutput {
	return i.ToKindClusterKindConfigNetworkingPtrOutputWithContext(context.Background())
}

func (i KindClusterKindConfigNetworkingArgs) ToKindClusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) KindClusterKindConfigNetworkingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigNetworkingOutput).ToKindClusterKindConfigNetworkingPtrOutputWithContext(ctx)
}

// KindClusterKindConfigNetworkingPtrInput is an input type that accepts KindClusterKindConfigNetworkingArgs, KindClusterKindConfigNetworkingPtr and KindClusterKindConfigNetworkingPtrOutput values.
// You can construct a concrete instance of `KindClusterKindConfigNetworkingPtrInput` via:
//
//	        KindClusterKindConfigNetworkingArgs{...}
//
//	or:
//
//	        nil
type KindClusterKindConfigNetworkingPtrInput interface {
	pulumi.Input

	ToKindClusterKindConfigNetworkingPtrOutput() KindClusterKindConfigNetworkingPtrOutput
	ToKindClusterKindConfigNetworkingPtrOutputWithContext(context.Context) KindClusterKindConfigNetworkingPtrOutput
}

type kindClusterKindConfigNetworkingPtrType KindClusterKindConfigNetworkingArgs

func KindClusterKindConfigNetworkingPtr(v *KindClusterKindConfigNetworkingArgs) KindClusterKindConfigNetworkingPtrInput {
	return (*kindClusterKindConfigNetworkingPtrType)(v)
}

func (*kindClusterKindConfigNetworkingPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**KindClusterKindConfigNetworking)(nil)).Elem()
}

func (i *kindClusterKindConfigNetworkingPtrType) ToKindClusterKindConfigNetworkingPtrOutput() KindClusterKindConfigNetworkingPtrOutput {
	return i.ToKindClusterKindConfigNetworkingPtrOutputWithContext(context.Background())
}

func (i *kindClusterKindConfigNetworkingPtrType) ToKindClusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) KindClusterKindConfigNetworkingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigNetworkingPtrOutput)
}

type KindClusterKindConfigNetworkingOutput struct{ *pulumi.OutputState }

func (KindClusterKindConfigNetworkingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KindClusterKindConfigNetworking)(nil)).Elem()
}

func (o KindClusterKindConfigNetworkingOutput) ToKindClusterKindConfigNetworkingOutput() KindClusterKindConfigNetworkingOutput {
	return o
}

func (o KindClusterKindConfigNetworkingOutput) ToKindClusterKindConfigNetworkingOutputWithContext(ctx context.Context) KindClusterKindConfigNetworkingOutput {
	return o
}

func (o KindClusterKindConfigNetworkingOutput) ToKindClusterKindConfigNetworkingPtrOutput() KindClusterKindConfigNetworkingPtrOutput {
	return o.ToKindClusterKindConfigNetworkingPtrOutputWithContext(context.Background())
}

func (o KindClusterKindConfigNetworkingOutput) ToKindClusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) KindClusterKindConfigNetworkingPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v KindClusterKindConfigNetworking) *KindClusterKindConfigNetworking {
		return &v
	}).(KindClusterKindConfigNetworkingPtrOutput)
}

func (o KindClusterKindConfigNetworkingOutput) ApiServerAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNetworking) *string { return v.ApiServerAddress }).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNetworkingOutput) ApiServerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNetworking) *int { return v.ApiServerPort }).(pulumi.IntPtrOutput)
}

func (o KindClusterKindConfigNetworkingOutput) DisableDefaultCni() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNetworking) *bool { return v.DisableDefaultCni }).(pulumi.BoolPtrOutput)
}

func (o KindClusterKindConfigNetworkingOutput) IpFamily() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNetworking) *string { return v.IpFamily }).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNetworkingOutput) KubeProxyMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNetworking) *string { return v.KubeProxyMode }).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNetworkingOutput) PodSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNetworking) *string { return v.PodSubnet }).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNetworkingOutput) ServiceSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNetworking) *string { return v.ServiceSubnet }).(pulumi.StringPtrOutput)
}

type KindClusterKindConfigNetworkingPtrOutput struct{ *pulumi.OutputState }

func (KindClusterKindConfigNetworkingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KindClusterKindConfigNetworking)(nil)).Elem()
}

func (o KindClusterKindConfigNetworkingPtrOutput) ToKindClusterKindConfigNetworkingPtrOutput() KindClusterKindConfigNetworkingPtrOutput {
	return o
}

func (o KindClusterKindConfigNetworkingPtrOutput) ToKindClusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) KindClusterKindConfigNetworkingPtrOutput {
	return o
}

func (o KindClusterKindConfigNetworkingPtrOutput) Elem() KindClusterKindConfigNetworkingOutput {
	return o.ApplyT(func(v *KindClusterKindConfigNetworking) KindClusterKindConfigNetworking {
		if v != nil {
			return *v
		}
		var ret KindClusterKindConfigNetworking
		return ret
	}).(KindClusterKindConfigNetworkingOutput)
}

func (o KindClusterKindConfigNetworkingPtrOutput) ApiServerAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KindClusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.ApiServerAddress
	}).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNetworkingPtrOutput) ApiServerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *KindClusterKindConfigNetworking) *int {
		if v == nil {
			return nil
		}
		return v.ApiServerPort
	}).(pulumi.IntPtrOutput)
}

func (o KindClusterKindConfigNetworkingPtrOutput) DisableDefaultCni() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *KindClusterKindConfigNetworking) *bool {
		if v == nil {
			return nil
		}
		return v.DisableDefaultCni
	}).(pulumi.BoolPtrOutput)
}

func (o KindClusterKindConfigNetworkingPtrOutput) IpFamily() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KindClusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.IpFamily
	}).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNetworkingPtrOutput) KubeProxyMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KindClusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.KubeProxyMode
	}).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNetworkingPtrOutput) PodSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KindClusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.PodSubnet
	}).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNetworkingPtrOutput) ServiceSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KindClusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.ServiceSubnet
	}).(pulumi.StringPtrOutput)
}

type KindClusterKindConfigNode struct {
	ExtraMounts          []KindClusterKindConfigNodeExtraMount       `pulumi:"extraMounts"`
	ExtraPortMappings    []KindClusterKindConfigNodeExtraPortMapping `pulumi:"extraPortMappings"`
	Image                *string                                     `pulumi:"image"`
	KubeadmConfigPatches []string                                    `pulumi:"kubeadmConfigPatches"`
	Labels               map[string]string                           `pulumi:"labels"`
	Role                 *string                                     `pulumi:"role"`
}

// KindClusterKindConfigNodeInput is an input type that accepts KindClusterKindConfigNodeArgs and KindClusterKindConfigNodeOutput values.
// You can construct a concrete instance of `KindClusterKindConfigNodeInput` via:
//
//	KindClusterKindConfigNodeArgs{...}
type KindClusterKindConfigNodeInput interface {
	pulumi.Input

	ToKindClusterKindConfigNodeOutput() KindClusterKindConfigNodeOutput
	ToKindClusterKindConfigNodeOutputWithContext(context.Context) KindClusterKindConfigNodeOutput
}

type KindClusterKindConfigNodeArgs struct {
	ExtraMounts          KindClusterKindConfigNodeExtraMountArrayInput       `pulumi:"extraMounts"`
	ExtraPortMappings    KindClusterKindConfigNodeExtraPortMappingArrayInput `pulumi:"extraPortMappings"`
	Image                pulumi.StringPtrInput                               `pulumi:"image"`
	KubeadmConfigPatches pulumi.StringArrayInput                             `pulumi:"kubeadmConfigPatches"`
	Labels               pulumi.StringMapInput                               `pulumi:"labels"`
	Role                 pulumi.StringPtrInput                               `pulumi:"role"`
}

func (KindClusterKindConfigNodeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*KindClusterKindConfigNode)(nil)).Elem()
}

func (i KindClusterKindConfigNodeArgs) ToKindClusterKindConfigNodeOutput() KindClusterKindConfigNodeOutput {
	return i.ToKindClusterKindConfigNodeOutputWithContext(context.Background())
}

func (i KindClusterKindConfigNodeArgs) ToKindClusterKindConfigNodeOutputWithContext(ctx context.Context) KindClusterKindConfigNodeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigNodeOutput)
}

// KindClusterKindConfigNodeArrayInput is an input type that accepts KindClusterKindConfigNodeArray and KindClusterKindConfigNodeArrayOutput values.
// You can construct a concrete instance of `KindClusterKindConfigNodeArrayInput` via:
//
//	KindClusterKindConfigNodeArray{ KindClusterKindConfigNodeArgs{...} }
type KindClusterKindConfigNodeArrayInput interface {
	pulumi.Input

	ToKindClusterKindConfigNodeArrayOutput() KindClusterKindConfigNodeArrayOutput
	ToKindClusterKindConfigNodeArrayOutputWithContext(context.Context) KindClusterKindConfigNodeArrayOutput
}

type KindClusterKindConfigNodeArray []KindClusterKindConfigNodeInput

func (KindClusterKindConfigNodeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]KindClusterKindConfigNode)(nil)).Elem()
}

func (i KindClusterKindConfigNodeArray) ToKindClusterKindConfigNodeArrayOutput() KindClusterKindConfigNodeArrayOutput {
	return i.ToKindClusterKindConfigNodeArrayOutputWithContext(context.Background())
}

func (i KindClusterKindConfigNodeArray) ToKindClusterKindConfigNodeArrayOutputWithContext(ctx context.Context) KindClusterKindConfigNodeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigNodeArrayOutput)
}

type KindClusterKindConfigNodeOutput struct{ *pulumi.OutputState }

func (KindClusterKindConfigNodeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KindClusterKindConfigNode)(nil)).Elem()
}

func (o KindClusterKindConfigNodeOutput) ToKindClusterKindConfigNodeOutput() KindClusterKindConfigNodeOutput {
	return o
}

func (o KindClusterKindConfigNodeOutput) ToKindClusterKindConfigNodeOutputWithContext(ctx context.Context) KindClusterKindConfigNodeOutput {
	return o
}

func (o KindClusterKindConfigNodeOutput) ExtraMounts() KindClusterKindConfigNodeExtraMountArrayOutput {
	return o.ApplyT(func(v KindClusterKindConfigNode) []KindClusterKindConfigNodeExtraMount { return v.ExtraMounts }).(KindClusterKindConfigNodeExtraMountArrayOutput)
}

func (o KindClusterKindConfigNodeOutput) ExtraPortMappings() KindClusterKindConfigNodeExtraPortMappingArrayOutput {
	return o.ApplyT(func(v KindClusterKindConfigNode) []KindClusterKindConfigNodeExtraPortMapping {
		return v.ExtraPortMappings
	}).(KindClusterKindConfigNodeExtraPortMappingArrayOutput)
}

func (o KindClusterKindConfigNodeOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNode) *string { return v.Image }).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNodeOutput) KubeadmConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v KindClusterKindConfigNode) []string { return v.KubeadmConfigPatches }).(pulumi.StringArrayOutput)
}

func (o KindClusterKindConfigNodeOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v KindClusterKindConfigNode) map[string]string { return v.Labels }).(pulumi.StringMapOutput)
}

func (o KindClusterKindConfigNodeOutput) Role() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNode) *string { return v.Role }).(pulumi.StringPtrOutput)
}

type KindClusterKindConfigNodeArrayOutput struct{ *pulumi.OutputState }

func (KindClusterKindConfigNodeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]KindClusterKindConfigNode)(nil)).Elem()
}

func (o KindClusterKindConfigNodeArrayOutput) ToKindClusterKindConfigNodeArrayOutput() KindClusterKindConfigNodeArrayOutput {
	return o
}

func (o KindClusterKindConfigNodeArrayOutput) ToKindClusterKindConfigNodeArrayOutputWithContext(ctx context.Context) KindClusterKindConfigNodeArrayOutput {
	return o
}

func (o KindClusterKindConfigNodeArrayOutput) Index(i pulumi.IntInput) KindClusterKindConfigNodeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) KindClusterKindConfigNode {
		return vs[0].([]KindClusterKindConfigNode)[vs[1].(int)]
	}).(KindClusterKindConfigNodeOutput)
}

type KindClusterKindConfigNodeExtraMount struct {
	ContainerPath *string `pulumi:"containerPath"`
	HostPath      *string `pulumi:"hostPath"`
}

// KindClusterKindConfigNodeExtraMountInput is an input type that accepts KindClusterKindConfigNodeExtraMountArgs and KindClusterKindConfigNodeExtraMountOutput values.
// You can construct a concrete instance of `KindClusterKindConfigNodeExtraMountInput` via:
//
//	KindClusterKindConfigNodeExtraMountArgs{...}
type KindClusterKindConfigNodeExtraMountInput interface {
	pulumi.Input

	ToKindClusterKindConfigNodeExtraMountOutput() KindClusterKindConfigNodeExtraMountOutput
	ToKindClusterKindConfigNodeExtraMountOutputWithContext(context.Context) KindClusterKindConfigNodeExtraMountOutput
}

type KindClusterKindConfigNodeExtraMountArgs struct {
	ContainerPath pulumi.StringPtrInput `pulumi:"containerPath"`
	HostPath      pulumi.StringPtrInput `pulumi:"hostPath"`
}

func (KindClusterKindConfigNodeExtraMountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*KindClusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (i KindClusterKindConfigNodeExtraMountArgs) ToKindClusterKindConfigNodeExtraMountOutput() KindClusterKindConfigNodeExtraMountOutput {
	return i.ToKindClusterKindConfigNodeExtraMountOutputWithContext(context.Background())
}

func (i KindClusterKindConfigNodeExtraMountArgs) ToKindClusterKindConfigNodeExtraMountOutputWithContext(ctx context.Context) KindClusterKindConfigNodeExtraMountOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigNodeExtraMountOutput)
}

// KindClusterKindConfigNodeExtraMountArrayInput is an input type that accepts KindClusterKindConfigNodeExtraMountArray and KindClusterKindConfigNodeExtraMountArrayOutput values.
// You can construct a concrete instance of `KindClusterKindConfigNodeExtraMountArrayInput` via:
//
//	KindClusterKindConfigNodeExtraMountArray{ KindClusterKindConfigNodeExtraMountArgs{...} }
type KindClusterKindConfigNodeExtraMountArrayInput interface {
	pulumi.Input

	ToKindClusterKindConfigNodeExtraMountArrayOutput() KindClusterKindConfigNodeExtraMountArrayOutput
	ToKindClusterKindConfigNodeExtraMountArrayOutputWithContext(context.Context) KindClusterKindConfigNodeExtraMountArrayOutput
}

type KindClusterKindConfigNodeExtraMountArray []KindClusterKindConfigNodeExtraMountInput

func (KindClusterKindConfigNodeExtraMountArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]KindClusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (i KindClusterKindConfigNodeExtraMountArray) ToKindClusterKindConfigNodeExtraMountArrayOutput() KindClusterKindConfigNodeExtraMountArrayOutput {
	return i.ToKindClusterKindConfigNodeExtraMountArrayOutputWithContext(context.Background())
}

func (i KindClusterKindConfigNodeExtraMountArray) ToKindClusterKindConfigNodeExtraMountArrayOutputWithContext(ctx context.Context) KindClusterKindConfigNodeExtraMountArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigNodeExtraMountArrayOutput)
}

type KindClusterKindConfigNodeExtraMountOutput struct{ *pulumi.OutputState }

func (KindClusterKindConfigNodeExtraMountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KindClusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (o KindClusterKindConfigNodeExtraMountOutput) ToKindClusterKindConfigNodeExtraMountOutput() KindClusterKindConfigNodeExtraMountOutput {
	return o
}

func (o KindClusterKindConfigNodeExtraMountOutput) ToKindClusterKindConfigNodeExtraMountOutputWithContext(ctx context.Context) KindClusterKindConfigNodeExtraMountOutput {
	return o
}

func (o KindClusterKindConfigNodeExtraMountOutput) ContainerPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNodeExtraMount) *string { return v.ContainerPath }).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNodeExtraMountOutput) HostPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNodeExtraMount) *string { return v.HostPath }).(pulumi.StringPtrOutput)
}

type KindClusterKindConfigNodeExtraMountArrayOutput struct{ *pulumi.OutputState }

func (KindClusterKindConfigNodeExtraMountArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]KindClusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (o KindClusterKindConfigNodeExtraMountArrayOutput) ToKindClusterKindConfigNodeExtraMountArrayOutput() KindClusterKindConfigNodeExtraMountArrayOutput {
	return o
}

func (o KindClusterKindConfigNodeExtraMountArrayOutput) ToKindClusterKindConfigNodeExtraMountArrayOutputWithContext(ctx context.Context) KindClusterKindConfigNodeExtraMountArrayOutput {
	return o
}

func (o KindClusterKindConfigNodeExtraMountArrayOutput) Index(i pulumi.IntInput) KindClusterKindConfigNodeExtraMountOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) KindClusterKindConfigNodeExtraMount {
		return vs[0].([]KindClusterKindConfigNodeExtraMount)[vs[1].(int)]
	}).(KindClusterKindConfigNodeExtraMountOutput)
}

type KindClusterKindConfigNodeExtraPortMapping struct {
	ContainerPort *int    `pulumi:"containerPort"`
	HostPort      *int    `pulumi:"hostPort"`
	ListenAddress *string `pulumi:"listenAddress"`
	Protocol      *string `pulumi:"protocol"`
}

// KindClusterKindConfigNodeExtraPortMappingInput is an input type that accepts KindClusterKindConfigNodeExtraPortMappingArgs and KindClusterKindConfigNodeExtraPortMappingOutput values.
// You can construct a concrete instance of `KindClusterKindConfigNodeExtraPortMappingInput` via:
//
//	KindClusterKindConfigNodeExtraPortMappingArgs{...}
type KindClusterKindConfigNodeExtraPortMappingInput interface {
	pulumi.Input

	ToKindClusterKindConfigNodeExtraPortMappingOutput() KindClusterKindConfigNodeExtraPortMappingOutput
	ToKindClusterKindConfigNodeExtraPortMappingOutputWithContext(context.Context) KindClusterKindConfigNodeExtraPortMappingOutput
}

type KindClusterKindConfigNodeExtraPortMappingArgs struct {
	ContainerPort pulumi.IntPtrInput    `pulumi:"containerPort"`
	HostPort      pulumi.IntPtrInput    `pulumi:"hostPort"`
	ListenAddress pulumi.StringPtrInput `pulumi:"listenAddress"`
	Protocol      pulumi.StringPtrInput `pulumi:"protocol"`
}

func (KindClusterKindConfigNodeExtraPortMappingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*KindClusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (i KindClusterKindConfigNodeExtraPortMappingArgs) ToKindClusterKindConfigNodeExtraPortMappingOutput() KindClusterKindConfigNodeExtraPortMappingOutput {
	return i.ToKindClusterKindConfigNodeExtraPortMappingOutputWithContext(context.Background())
}

func (i KindClusterKindConfigNodeExtraPortMappingArgs) ToKindClusterKindConfigNodeExtraPortMappingOutputWithContext(ctx context.Context) KindClusterKindConfigNodeExtraPortMappingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigNodeExtraPortMappingOutput)
}

// KindClusterKindConfigNodeExtraPortMappingArrayInput is an input type that accepts KindClusterKindConfigNodeExtraPortMappingArray and KindClusterKindConfigNodeExtraPortMappingArrayOutput values.
// You can construct a concrete instance of `KindClusterKindConfigNodeExtraPortMappingArrayInput` via:
//
//	KindClusterKindConfigNodeExtraPortMappingArray{ KindClusterKindConfigNodeExtraPortMappingArgs{...} }
type KindClusterKindConfigNodeExtraPortMappingArrayInput interface {
	pulumi.Input

	ToKindClusterKindConfigNodeExtraPortMappingArrayOutput() KindClusterKindConfigNodeExtraPortMappingArrayOutput
	ToKindClusterKindConfigNodeExtraPortMappingArrayOutputWithContext(context.Context) KindClusterKindConfigNodeExtraPortMappingArrayOutput
}

type KindClusterKindConfigNodeExtraPortMappingArray []KindClusterKindConfigNodeExtraPortMappingInput

func (KindClusterKindConfigNodeExtraPortMappingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]KindClusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (i KindClusterKindConfigNodeExtraPortMappingArray) ToKindClusterKindConfigNodeExtraPortMappingArrayOutput() KindClusterKindConfigNodeExtraPortMappingArrayOutput {
	return i.ToKindClusterKindConfigNodeExtraPortMappingArrayOutputWithContext(context.Background())
}

func (i KindClusterKindConfigNodeExtraPortMappingArray) ToKindClusterKindConfigNodeExtraPortMappingArrayOutputWithContext(ctx context.Context) KindClusterKindConfigNodeExtraPortMappingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KindClusterKindConfigNodeExtraPortMappingArrayOutput)
}

type KindClusterKindConfigNodeExtraPortMappingOutput struct{ *pulumi.OutputState }

func (KindClusterKindConfigNodeExtraPortMappingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KindClusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (o KindClusterKindConfigNodeExtraPortMappingOutput) ToKindClusterKindConfigNodeExtraPortMappingOutput() KindClusterKindConfigNodeExtraPortMappingOutput {
	return o
}

func (o KindClusterKindConfigNodeExtraPortMappingOutput) ToKindClusterKindConfigNodeExtraPortMappingOutputWithContext(ctx context.Context) KindClusterKindConfigNodeExtraPortMappingOutput {
	return o
}

func (o KindClusterKindConfigNodeExtraPortMappingOutput) ContainerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNodeExtraPortMapping) *int { return v.ContainerPort }).(pulumi.IntPtrOutput)
}

func (o KindClusterKindConfigNodeExtraPortMappingOutput) HostPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNodeExtraPortMapping) *int { return v.HostPort }).(pulumi.IntPtrOutput)
}

func (o KindClusterKindConfigNodeExtraPortMappingOutput) ListenAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNodeExtraPortMapping) *string { return v.ListenAddress }).(pulumi.StringPtrOutput)
}

func (o KindClusterKindConfigNodeExtraPortMappingOutput) Protocol() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KindClusterKindConfigNodeExtraPortMapping) *string { return v.Protocol }).(pulumi.StringPtrOutput)
}

type KindClusterKindConfigNodeExtraPortMappingArrayOutput struct{ *pulumi.OutputState }

func (KindClusterKindConfigNodeExtraPortMappingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]KindClusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (o KindClusterKindConfigNodeExtraPortMappingArrayOutput) ToKindClusterKindConfigNodeExtraPortMappingArrayOutput() KindClusterKindConfigNodeExtraPortMappingArrayOutput {
	return o
}

func (o KindClusterKindConfigNodeExtraPortMappingArrayOutput) ToKindClusterKindConfigNodeExtraPortMappingArrayOutputWithContext(ctx context.Context) KindClusterKindConfigNodeExtraPortMappingArrayOutput {
	return o
}

func (o KindClusterKindConfigNodeExtraPortMappingArrayOutput) Index(i pulumi.IntInput) KindClusterKindConfigNodeExtraPortMappingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) KindClusterKindConfigNodeExtraPortMapping {
		return vs[0].([]KindClusterKindConfigNodeExtraPortMapping)[vs[1].(int)]
	}).(KindClusterKindConfigNodeExtraPortMappingOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*KindClusterKindConfigInput)(nil)).Elem(), KindClusterKindConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*KindClusterKindConfigPtrInput)(nil)).Elem(), KindClusterKindConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*KindClusterKindConfigNetworkingInput)(nil)).Elem(), KindClusterKindConfigNetworkingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*KindClusterKindConfigNetworkingPtrInput)(nil)).Elem(), KindClusterKindConfigNetworkingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*KindClusterKindConfigNodeInput)(nil)).Elem(), KindClusterKindConfigNodeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*KindClusterKindConfigNodeArrayInput)(nil)).Elem(), KindClusterKindConfigNodeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*KindClusterKindConfigNodeExtraMountInput)(nil)).Elem(), KindClusterKindConfigNodeExtraMountArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*KindClusterKindConfigNodeExtraMountArrayInput)(nil)).Elem(), KindClusterKindConfigNodeExtraMountArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*KindClusterKindConfigNodeExtraPortMappingInput)(nil)).Elem(), KindClusterKindConfigNodeExtraPortMappingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*KindClusterKindConfigNodeExtraPortMappingArrayInput)(nil)).Elem(), KindClusterKindConfigNodeExtraPortMappingArray{})
	pulumi.RegisterOutputType(KindClusterKindConfigOutput{})
	pulumi.RegisterOutputType(KindClusterKindConfigPtrOutput{})
	pulumi.RegisterOutputType(KindClusterKindConfigNetworkingOutput{})
	pulumi.RegisterOutputType(KindClusterKindConfigNetworkingPtrOutput{})
	pulumi.RegisterOutputType(KindClusterKindConfigNodeOutput{})
	pulumi.RegisterOutputType(KindClusterKindConfigNodeArrayOutput{})
	pulumi.RegisterOutputType(KindClusterKindConfigNodeExtraMountOutput{})
	pulumi.RegisterOutputType(KindClusterKindConfigNodeExtraMountArrayOutput{})
	pulumi.RegisterOutputType(KindClusterKindConfigNodeExtraPortMappingOutput{})
	pulumi.RegisterOutputType(KindClusterKindConfigNodeExtraPortMappingArrayOutput{})
}
