# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_kind.v1alpha4 as __v1alpha4
    v1alpha4 = __v1alpha4
else:
    v1alpha4 = _utilities.lazy_import('pulumi_kind.v1alpha4')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "kind",
  "mod": "v1alpha4/kindCluster",
  "fqn": "pulumi_kind.v1alpha4",
  "classes": {
   "kind:v1alpha4/kindCluster:KindCluster": "KindCluster"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "kind",
  "token": "pulumi:providers:kind",
  "fqn": "pulumi_kind",
  "class": "Provider"
 }
]
"""
)
